<?php $this->layout('layout::default', $this->data()) ?>

<div class="container">
    <div class="row align-items-center justify-content-md-center">
        <div class="col-md-5">
            <h1><?=$this->translate('Restricted area')?></h1>
            <form method="post" action="<?=$this->url('login')?>" class="card" autocomplete="off">
                <div class="card-body">
                <?php if (!empty($message)) : ?>
                    <p class="text-warning"><?=$message?></p>
                    <hr>
                <?php endif ?>
                    <div class="form-group">
                        <label class="control-label" for="inputLogin"><?=$this->translate('Login')?></label>
                        <input class="form-control" id="inputLogin" name="login" required="required" type="text">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputPassword"><?=$this->translate('Password')?></label>
                        <input class="form-control" id="inputPassword" name="password" required="required" type="password">
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="inputLanguage"><?=$this->translate('Language')?></label>
                        <select class="form-control" name="lang" id="inputLanguage">
                            <option value="fr">Fran&ccedil;ais</option>
                            <option value="nl">Nederlands</option>
                            <option value="en">English</option>
                        </select>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="fas fa-sign-in-alt"></i>
                            <?=$this->translate('Log in')?>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
