<div class="modal" id="modal-info" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-info-circle"></i> <?=$this->translate('Information')?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        <table class="table table-striped table-sm">
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="col-6">
                        <i id="note-success" class="far fa-check-circle float-right text-success"></i>
                        <strong><?=$this->translate('Note')?> :</strong>
                        <form action="/app/check-points/api/object/" method="post">
                            <textarea class="form-control" name="note" id="note" style="min-height: 250px;"></textarea>
                            <button type="submit" class="btn btn-primary btn-block mt-1">
                                <i class="far fa-save"></i>
                                <?=$this->translate('Save')?>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
